% Question 2 Flowered FST

transition(1,aa,2,aa).
transition(1,ae,2,ae).
transition(1,ah,2,ah).
transition(1,ao,2,ao).
transition(1,aw,2,aw).
transition(1,ay,2,ay).
transition(1,ch,2,ch).
transition(1,d,2,d).
transition(1,dh,2,dh).
transition(1,eh,2,eh).
transition(1,er,2,er).
transition(1,ey,2,ey).
transition(1,f,2,f).
transition(1,hh,2,hh).
transition(1,ih,2,ih).
transition(1,iy,2,iy).
transition(1,jh,2,jh).
transition(1,l,2,l).
transition(1,m,2,m).
transition(1,n,2,n).
transition(1,ow,2,ow).
transition(1,oy,2,oy).
transition(1,r,2,r).
transition(1,sh,2,sh).
transition(1,t,2,t).
transition(1,th,2,th).
transition(1,uh,2,uh).
transition(1,uw,2,uw).
transition(1,v,2,v).
transition(1,w,2,w).
transition(1,y,2,y).
transition(1,zh,2,zh).
transition(1,p,3,b).
transition(1,p,4,p).
transition(1,b,5,b).
transition(1,b,6,p).
transition(1,t,7,d).
transition(1,t,8,t).
transition(1,d,9,t).
transition(1,d,10,d).
transition(1,s,11,s).
transition(1,s,12,z).
transition(1,z,13,z).
transition(1,z,13,s).
transition(2,eps,1,eps).
transition(3,eps,1,eps).
transition(4,eps,1,eps).
transition(5,eps,1,eps).
transition(6,eps,1,eps).
transition(7,eps,1,eps).
transition(8,eps,1,eps).
transition(9,eps,1,eps).
transition(10,eps,1,eps).
transition(11,eps,1,eps).
transition(12,eps,1,eps).
transition(13,eps,1,eps).
transition(14,eps,1,eps).
initial(1).
final(1).
