% Question 3

transition(1,aa,1,aa).
transition(1,ae,1,ae).
transition(1,ah,1,ah).
transition(1,ao,1,aw).
transition(1,aw,1,aw).
transition(1,ay,1,ay).
transition(1,b,1,b).
transition(1,ch,1,ch).
transition(1,d,1,d).
transition(1,dh,1,dh).
transition(1,eh,1,eh).
transition(1,er,1,er).
transition(1,ey,1,ey).
transition(1,f,1,f).
transition(1,d,1,d).
transition(1,dh,1,dh).
transition(1,dhe,1,dhe).
transition(1,di,1,di).
transition(1,t,1,t).
transition(1,u,1,u).
transition(1,v,1,v).
transition(1,n,1,n).
transition(1,ow,1,ow).
transition(1,oy,1,oy).
transition(1,p,1,p).
transition(1,r,1,r).
transition(1,s,1,s).
transition(1,sh,1,sh).
transition(1,t,1,t).
transition(1,th,1,th).
transition(1,uh,1,uh).
transition(1,uw,1,uw).
transition(1,v,1,v).
transition(1,w,1,w).
transition(1,y,1,y).
transition(1,z,1,z).
transition(1,zh,1,zh).

transition(1,b,2,p).
transition(1,p,2,b).
transition(1,t,2,d).
transition(1,d,2,t).
transition(1,s,2,z).
transition(1,z,2,s).

transition(2,aa,2,aa).
transition(2,ae,2,ae).
transition(2,ah,1,ah).
transition(2,ao,1,aw).
transition(2,aw,1,aw).
transition(2,ay,1,ay).
transition(2,b,2,b).
transition(2,ch,2,ch).
transition(2,d,2,d).
transition(2,dh,2,dh).
transition(2,eh,2,eh).
transition(2,er,2,er).
transition(2,ey,2,ey).
transition(2,f,2,f).
transition(2,d,2,d).
transition(2,dh,2,dh).
transition(2,dhe,2,dhe).
transition(2,di,2,di).
transition(2,t,2,t).
transition(2,u,2,u).
transition(2,v,2,v).
transition(2,n,2,n).
transition(2,ow,2,ow).
transition(2,oy,2,oy).
transition(2,p,2,p).
transition(2,r,2,r).
transition(2,s,2,s).
transition(2,sh,2,sh).
transition(2,t,2,t).
transition(2,th,2,th).
transition(2,uh,2,uh).
transition(2,uw,2,uw).
transition(2,v,2,v).
transition(2,w,2,w).
transition(2,y,2,y).
transition(2,z,2,z).
transition(2,zh,2,zh).

initial(1).
final(2).

